{% set name = "graspologic" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graspologic-{{ version }}.tar.gz
  sha256: 08fe052694a027995b3222d01d8cb64e1bf242e7915a5016268927c64f6229fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools >=24.2.0
    - pip
  run:
    - python >=3.8,<3.12
    - anytree >=2.8.0
    - beartype >=0.10.0
    - gensim >=4.0.0,!=4.2.0
    - graspologic-native >=1.1.1
    - hyppo >=0.3.2
    - joblib >=0.17.0
    - matplotlib-base >=3.0.0,!=3.3.*,!=3.6.1
    - networkx >=2.1
    - numpy >=1.8.1
    - pot >=0.7.0
    - seaborn >=0.11.0
    - scikit-learn >=0.22.0
    - scipy >=1.9.0
    - statsmodels >=0.13.2
    - typing-extensions >=4.4.0
    - umap-learn >=0.4.6

test:
  imports:
    - graspologic
    - graspologic.partition.leiden
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/graspologic
  summary: A set of python modules for graph statistics
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - johandahlberg
